CREATE DATABASE TestSecurity1;


CREATE TABLE EMP(
 Id CHAR(3) PRIMARY KEY,
 Name VARCHAR(10)
);

CREATE LOGIN reader1 WITH PASSWORD ='login@123';

CREATE USER Amal1 FOR LOGIN reader1;

GRANT SELECT, INSERT ON EMP TO Amal;

INSERT INTO EMP VALUES('001','Perera');
SELECT * FROM EMP;

DELETE FROM EMP;
